info = open("info.txt","a")
info.write("\nMy name is Md. Wahid Ullah.\n")
info.write("I'm graduated from DUET\n")
info.write("My District is Chattogram.\n")
info.write("I'm an employee of Haque publication.\n")
info.write("My position is Research & Writer.\n")
info.write("My Contact id is https://www.fb.com/mdwahidullah.rajo\n")
info.write("Company's id is https://www.fb.com/haquepublications")
info.close()
